version: '3.8'
services:
  db:
    image: mariadb:11
    container_name: estoque-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: estoque
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
